# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', geoposition.fields.GeopositionField(max_length=42)),
                ('geotag', models.ManyToManyField(related_name='zones', to='places.GeoTag')),
                ('member', models.ManyToManyField(through='events.CheckIn', to=settings.AUTH_USER_MODEL)),
                ('member_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Location')),
            ],
        ),
    ]
