# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='zone',
            field=models.ManyToManyField(related_name='zones', to='places.Zone'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='geotag',
            field=models.ManyToManyField(related_name='geotags', to='places.GeoTag'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checked_into', to='events.Journey'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='places.Zone'),
        ),
    ]
